# Generated by Django 3.2.8 on 2022-01-22 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Expired', 'Expired'), ('NOT Expired', 'NOT Expired')], max_length=50, null=True)),
                ('user_has_voted', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-expire_at'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=255)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_poll', to='polls.question')),
            ],
        ),
    ]
